server:
  port: 8082

spring:
  redis:
    database: 0
#    host: 192.168.43.57
    host: 192.168.31.17
    port: 6379

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://192.168.43.57:3306/dance?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    url: jdbc:mysql://192.168.31.17:3306/dance?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: dance
    password: dance


# 让mapper接口显示SQL语句
logging:
  level:
    com:
      mini:
        blog: debug
# 声明mapper.xml的位置
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml