server:
  port: 8085
  tomcat:
    uri-encoding: UTF-8
  max-http-header-size: 80KB

spring:
  redis:
    database: 0
#    host: 192.168.31.17
    host: 192.168.56.101
    port: 6379

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.56.101:3306/dance?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
#    url: jdbc:mysql://192.168.31.17:3306/dance?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: dance
    password: dance
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 600000
      pool-name: DataSourceHikariCP
      max-lifetime: 1800000
      connection-test-query: SELECT 1

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 20MB


# 让mapper接口显示SQL语句
logging:
  level:
    com:
      mini:
        blog: debug
# 声明mapper.xml的位置
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    cache-enabled: true

jwt:
  key: bPem0BaWWLT8oYg7NGLsDhKLlTqfgIYVaQex5vDN8Qc= #JWT密钥
  expiration: 20 #过期时间

storage:
  address: http://127.0.0.1:8085/image/
  location: /data/image/
  uri-prefix: /data/